POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "number": "012-3456789"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "John Smith"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "John Smith",
  "number": "012-345789"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Liisa Marttinen",
  "number": "040-243563"
}