DELETE http://localhost:3001/api/persons/1

###

DELETE http://localhost:3001/api/persons/99

###

DELETE http://localhost:3001/api/persons/99

###

DELETE http://localhost:3001/api/persons/6577743b76f89b96de61cf27

###

DELETE http://localhost:3001/api/persons/SomeNonExistentID