POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog",
  "author": "Test Author",
  "url": "http://test.com",
  "userId": "659b27489588a4a4906dbd80",
  "likes": 0
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "First Blog",
  "author": "First Author",
  "url": "http://first.com",
  "userId": "659b27489588a4a4906dbd80",
  "likes": 9
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Second Blog",
  "author": "Second Author",
  "url": "http://second.com",
  "userId": "659dc1e2380d5b2a5fb6c640",
  "likes": 4
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Third Blog",
  "author": "Third Author",
  "url": "http://third.com",
  "userId": "659dc1e2380d5b2a5fb6c640",
  "likes": 11
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Fourth Blog",
  "author": "Fourth Author",
  "url": "http://fourth.com",
  "userId": "659dc1e4380d5b2a5fb6c644",
  "likes": 2
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZpcnN0LVVzZXIiLCJpZCI6IjY1OWIyNzQ4OTU4OGE0YTQ5MDZkYmQ4MCIsImlhdCI6MTcwNDg0MDI2MX0.SGZMcdsmkE_e227gl3WWt1YuIpxmrwX_pVF5PlddrAI

{
  "title": "Testing Authorization",
  "author": "Test Author",
  "url": "http://github.com",
  "likes": 12
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNlY29uZC1Vc2VyIiwiaWQiOiI2NTlkYzFlMjM4MGQ1YjJhNWZiNmM2NDAiLCJpYXQiOjE3MDQ4NDc2NDN9.DAcj5OtwJ7tkRGdJWazdLPVH-U5cWjVANMxU8-4UdOk

{
  "title": "Testing For Second User",
  "author": "Test Author 2",
  "url": "http://github.com",
  "likes": 11
}
